FROM debian:forky

RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    wget \
    git \
    gcc \
    libc6-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# 1. 设置环境变量，这样后续所有 RUN 指令都能找到 rust 命令
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

# 2. 安装 Rust
RUN set -eux; \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path; \
    # 验证安装
    rustc --version; \
    cargo --version; \
    # (可选) 给予其他用户执行权限
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME;

WORKDIR /workspace

CMD ["/bin/bash"]
